development:
  spotify_id: <%= ENV["SPOTIFY_CLIENT_ID"] %>
  spotify_secret: <%= ENV["SPOTIFY_CLIENT_SECRET"] %>
test:
  spotify_id: <%= ENV["SPOTIFY_CLIENT_ID"] %>
  spotify_secret: <%= ENV["SPOTIFY_CLIENT_SECRET"] %>
production:
  spotify_id: <%= ENV["SPOTIFY_CLIENT_ID"] %>
  spotify_secret: <%= ENV["SPOTIFY_CLIENT_SECRET"] %>